OPTIONS COMPRESS=YES;
OPTIONS NOXWAIT;

*%INCLUDE "E:\KAUFMANN\SAS\LIBRERIAS.SAS"/SOURCE2;

/*PV WAS HERE :)*/

DATA A;
SET KAUFMANN.CALENDARIO;
FECHA_EXTRACCION=datepart(DATETIME());
FORMAT FECHA_EXTRACCION ddmmyy10.; 

IF DIA=day(FECHA_EXTRACCION) AND MES=month(FECHA_EXTRACCION) AND ANIO=year(FECHA_EXTRACCION);
IF DIA=2 THEN ID=ID-1;
*IF DIA=3 THEN ID=ID-2;
*IF DIA=4 THEN ID=ID-3;

DIA_SEMANA=WEEKday(FECHA_EXTRACCION);
IF DIA_SEMANA=4 THEN DESC_DIA_SEMANA='MIERCOLES';
IF DIA_SEMANA=5 THEN DESC_DIA_SEMANA='JUEVES';
IF DIA_SEMANA=6 THEN DESC_DIA_SEMANA='VIERNES';
IF DIA_SEMANA=7 THEN DESC_DIA_SEMANA='SABADO';
IF DIA_SEMANA=1 THEN DESC_DIA_SEMANA='DOMINGO';
IF DIA_SEMANA=2 THEN DESC_DIA_SEMANA='LUNES';
IF DIA_SEMANA=3 THEN DESC_DIA_SEMANA='MARTES';

IF DIA_SEMANA=2 and DIA=3 THEN DO;
IF DIA=3 THEN ID=ID-2;
END;

RUN;

proc sql noprint;
	SELECT ID-1 into:ID
      FROM A;
	quit;

%put &ID;

DATA FECHA1;
SET KAUFMANN.CALENDARIO;
IF ID=&ID.;

FORMAT MES $2.;
INFORMAT MES $2.;

FORMAT ANIO $4.;
INFORMAT ANIO $4.;

LENGTH M $ 10;

IF MES=1 THEN DO;M='ENERO';END;
IF MES=2 THEN DO;M='FEBRERO';END;
IF MES=3 THEN DO;M='MARZO';END;
IF MES=4 THEN DO;M='ABRIL';END;
IF MES=5 THEN DO;M='MAYO';END;
IF MES=6 THEN DO;M='JUNIO';END;
IF MES=7 THEN DO;M='JULIO';END;
IF MES=8 THEN DO;M='AGOSTO';END;
IF MES=9 THEN  DO;M='SEPTIEMBRE';END;
IF MES=10 THEN DO;M='OCTUBRE';;END;
IF MES=11 THEN DO;M='NOVIEMBRE';END;
IF MES=12 THEN DO;M='DICIEMBRE';END;

L=LENGTH(M);
FECHA_EXTRACCION=datepart(DATETIME());
RUN;


proc sql noprint;
	SELECT L into:L
      FROM FECHA1;
	quit;

%put &L;

DATA FECHA2;
LENGTH M $&L.;
SET FECHA1;

RUN;

proc sql noprint;
	SELECT ANIO into:ANIO
      FROM FECHA2;
	quit;

proc sql noprint;
	SELECT MES into:MES
      FROM FECHA2;
	quit;

proc sql noprint;
	SELECT DIA into:DIA
      FROM FECHA2;
	quit;


proc sql noprint;
	SELECT M into:M
      FROM FECHA2;

proc sql noprint;
	SELECT WEEKDAY(FECHA_EXTRACCION) into:DIA_SEMANA
      FROM FECHA2;
	quit;

%put &DIA_SEMANA;

%put &DIA;
%put &MES;
%put &ANIO;
%put &M;

	quit;
